#INCLUDE "protheus.ch"
#INCLUDE "TOTVS.ch"

/*/{Protheus.doc} nomeFunction
    (long_description)
    @type  Function
    @author user
    @since 16/11/2021
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
User Function OlaMundo()
    MsgInfo("Olá Mundo do Protheus !", "Primeira Aula - Semana Dev")
Return 
