--adapter
SELECT B1_COD,B1_DESC,B1_GRUPO,BM_DESC
FROM	SB1990 SB1 LEFT JOIN SBM990 SBM
ON B1_GRUPO = BM_GRUPO 
AND BM_FILIAL = B1_FILIAL 
AND SBM.D_E_L_E_T_ =  SB1.D_E_L_E_T_ 

--WsProdutos
SELECT SB1.B1_COD CODE,SB1.B1_DESC DESCRICAO,SB1.B1_GRUPO COD_GRUPO,SBM.BM_DESC GRUPO
FROM	SB1990 SB1 LEFT JOIN SBM990 SBM
ON		SB1.B1_GRUPO = SBM.BM_GRUPO 
AND		SB1.B1_FILIAL = SBM.BM_FILIAL
AND		SB1.D_E_L_E_T_ = SBM.D_E_L_E_T_
WHERE	SB1.B1_FILIAL ='01' 
AND		SB1.D_E_L_E_T_ =  '' 

SELECT * FROm SB1990
SELECT * FROm SBM990

