SELECT	A1_COD as cod,A1.A1_NOME as Cliente,F2_EMISSAO as Emissao,F2.F2_VALBRUT as Total
FROM	SF2990 F2 INNER JOIN SA1990 A1
ON		F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA
AND		A1.D_E_L_E_T_ = F2.D_E_L_E_T_
WHERE	F2.D_E_L_E_T_ = ''
--GROUP BY  A1_COD,A1_NOME,F2_EMISSAO,F2_VALBRUT

SELECT	A1.A1_NOME as Cliente,SUM(F2.F2_VALBRUT) as Total
FROM	SF2990 F2 INNER JOIN SA1990 A1
ON		F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA
AND		A1.D_E_L_E_T_ = F2.D_E_L_E_T_
WHERE	F2.D_E_L_E_T_ = ''
GROUP BY  A1_NOME



