/*PEDIDOS DE COMPRA POR FORNECEDOR*/
SELECT A2_COD, A2_NOME, C7_NUM, C7_EMISSAO,C7_PRODUTO, C7_QUANT FROM SC7990 SC7
INNER JOIN SA2990 SA2 ON SC7.C7_FORNECE = SA2.A2_COD AND SC7.C7_LOJA = SA2.A2_LOJA 

/*PEDIDOS DE VENDA*/
SELECT C5_NUM,A1_NOME, C5_EMISSAO, C6_PRODUTO, C6_QTDVEN, C6_PRCVEN,C6_VALOR FROM SC5990 SC5
INNER JOIN SC6990 AS SC6 ON SC5.C5_NUM = C6_NUM AND C5_SERIE = C6_SERIE AND SC6.D_E_L_E_T_ = ' '
INNER JOIN SA1990 AS SA1 ON SC5.C5_CLIENTE = A1_COD AND C5_LOJACLI = A1_LOJA  AND SA1.D_E_L_E_T_ = ' '
WHERE SC5.D_E_L_E_T_ = ' ' AND (C5_CLIENTE BETWEEN '' AND 'ZZZZZZ' AND C5_NUM BETWEEN '' AND 'ZZZZZ'



/*NOTAS FISCAIS DE SAÍDA**/
SELECT F2_DOC, F2_SERIE, A1_NOME,F2_VALBRUT FROM SF2990 AS SF2
INNER JOIN SA1990 AS SA1 ON SF2.F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA AND SA1.D_E_L_E_T_ = ' '
WHERE SF2.D_E_L_E_T_ = ' '


/*ITENS DAS NOTAS FISCAIS DE SAIDA*/
SELECT F2_DOC, F2_SERIE, A1_NOME, D2_COD, D2_QUANT, D2_TOTAL	 FROM SF2990 AS SF2
INNER JOIN SD2990 AS SD2 ON SF2.F2_DOC = SD2.D2_DOC AND F2_SERIE = D2_SERIE AND D2_FILIAL = F2_FILIAL AND SD2.D_E_L_E_T_ = ' '
INNER JOIN SA1990 AS SA1 ON SF2.F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA  AND F2_FILIAL = A1_FILIAL  AND SA1.D_E_L_E_T_ = ' '
INNER JOIN SB1990 AS SB1 ON SD2.D2_COD = B1_COD AND B1_FILIAL = D2_FILIAL AND SB1.D_E_L_E_T_ = ' '
WHERE SF2.D_E_L_E_T_ = ' '

/*NOTAS FISCAIS DE ENTRADA*/
SELECT F1_DOC , F1_SERIE, A2_NOME, F1_EMISSAO, F1_VALBRUT FROM SF1990 AS SF1
INNER JOIN SA2990 AS SA2 ON SF1.F1_FORNECE = A2_COD AND F1_LOJA = A2_LOJA AND SA2.D_E_L_E_T_ = ' '
AND SF1.D_E_L_E_T_ = ' '


/*ITENS DAS NOTAS FISCAIS DE ENTRADA*/
SELECT F1_DOC , F1_SERIE, A2_NOME, F1_EMISSAO, B1_COD, B1_DESC, D1_QUANT, D1_TOTAL FROM SF1990 AS SF1
INNER JOIN SD1990 AS SD1 ON SF1.F1_DOC = D1_DOC AND F1_SERIE = D1_SERIE AND 
F1_FORNECE = D1_FORNECE AND F1_FILIAL = D1_FILIAL AND SD1.D_E_L_E_T_ = ' '
INNER JOIN SA2990 AS SA2 ON SF1.F1_FORNECE = A2_COD AND F1_LOJA = A2_LOJA AND SA2.D_E_L_E_T_ = ' '
INNER JOIN SB1990 AS SB1 ON SD1.D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL AND SB1.D_E_L_E_T_ = ' '
AND SF1.D_E_L_E_T_ = ' '